### ISSUE TITLE
State is null and causes component deletion failure

### ISSUE THREAD

**Issue by lichenglu** [thunkable/thunkable-issues#1015]
The state is null and causes component deletion failure. I think this is also related to another issue that component is not shown at the correct position (e.g., `Get Started` button)

### Platform
I am new to Thunkable, so I am not sure which platform I should fill. It is the DnD web interface of Thunkable X. So I guess it is not the classic platform.

### Issue/Request Origin
From my student

### Steps to Reproduce
1. You can find the project here: https://x.thunkable.com/copy/c1db6f27fff246cb56c495ddc4d5f766
2. Try to delete any component (e.g., Home Screen → Get Started button)
3. Nothing is deleted
4. Check the browser console, and there will be an error “Cannot convert undefined or null to object”
5. This error is related to a redux reducer, I believe. The state (variables.js) is somehow null, which I think is unexpected.
![image|689x340](https://aws1.discourse-cdn.com/business4/uploads/thunkable1/original/3X/6/f/6fca6928c7fa5eac6b13c93e3c8dbd1f2880b04a.png)

### Project Link
https://x.thunkable.com/copy/c1db6f27fff246cb56c495ddc4d5f766

### Expected Behavior
When you try to delete a component, the component will be deleted.

### Actual Behavior
Nothing is deleted.

I noticed there was an issue with the Thunkable server yesterday afternoon. And the student was working on the project during the time. Creating a freshly new project does NOT have this issue. However, this is still serious, imagine someone has spent weeks on the project, and suddenly the project is corrupted and she/he needs to start over.

**Comment by weihuali0509** [comment]
Hi @lichenglu, we just deployed a fix for it. Can you please confirm if the project work for you as expected now? 

Thank you,
Wei

**Comment by lichenglu** [comment]
> Hi @lichenglu, we just deployed a fix for it. Can you please confirm if the project work for you as expected now?
> 
> Thank you,
> Wei

Thank you for addressing the issue promptly! I can confirm the deletion issue is gone now. 

However, there is still an issue with the incorrect positioning. For example, in  `HomeScreen`, there is a `Tutorial button` placed both horizontally and vertically center (almost). But when I enter `web preview`, the button is shown on the bottom-right corner. It is weird that it seems the redux store does record the correct coordinates of `Tutorial button`, but somehow it is not placed on the right spot when rendering. Maybe there are some issues with how `xy` are converted to CSS position properties (top & left)?

![image](https://user-images.githubusercontent.com/14342440/132764583-685a05bd-17a6-47f4-b81c-65d51ceddfae.png)

**Comment by weihuali0509** [comment]
Please create a new ticket for the potential issue.
