### ISSUE TITLE
Text substring off by one character

### ISSUE THREAD

**Issue by AmigoDeluxe** [thunkable/thunkable-issues#182]
### Platform
✕, ✕ Android companion (I don't have an iOS device to check with)

### Description
I am using the Text > Get Substring functionality to trim strings I first retrieve using API calls and get the characters from position i.e. 3 to position 6 of the string. Initially this works but sometimes the returned substring is from position 4 to position 7! I have noticed that if I move a block even slightly in the affected screen and re-test the app, the issue goes away and I again get the correct substring (3 to 6).

I then create a second screen which does the same thing for a different string from position i.e. 5 to position 8 and very quickly experience the same issue described above. I then move a block in the second screen to "fix" the issue as I did for the first screen and indeed, it does fix it for the second screen but at the same time it breaks it for the first screen!!!

### Steps to Reproduce
Described above

### Expected Behavior
Always get the correct substrings

### Actual Behavior
Substrings are off by one character

**Comment by AlexITMan** [comment]
If you give a link to your project, then I will check it on iOS. There is a problem with indexes when working with the list, but I did not notice this with the text.

**Comment by AmigoDeluxe** [comment]
Hey @AlexITMan , it looks like it is a known issue: https://github.com/thunkable/thunkable-issues/issues/37#issuecomment-433199235

The question is if Thunkable is still working on a solution...

**Comment by mark-friedman** [comment]
@AmigoDeluxe We're investigating.

**Comment by AlexITMan** [comment]
> 
> 
> Hey @AlexITMan , it looks like it is a known issue: [#37 (comment)](https://github.com/thunkable/thunkable-issues/issues/37#issuecomment-433199235)
> 
> The question is if Thunkable is still working on a solution...

Let's clarify the question. In # 37 I wrote about the error associated with indexing the list. You write that there is a problem with text indexing when using the "get substring" block. You want to say that the "get substring" block also has an error that "get # from list" has? I did not know this and then the situation looks even worse.

**Comment by mark-friedman** [comment]
@AlexITMan It turns out that the both issues have the same underlying cause.  The fix should be in the next release of Thunkable ✕.

**Comment by AlexITMan** [comment]
Thank you, Mark, for clarifying the situation. I didn't know that.

**Comment by mark-friedman** [comment]
@AmigoDeluxe Do you have a simple app that you could share which demonstrates the problem?  I'd like to make sure that our fix actually fixes what you are seeing.

**Comment by AmigoDeluxe** [comment]
Hey @mark-friedman 

Sure: https://x.thunkable.com/copy/3b6c014e65b8e2f231af32b36ab86f1c

Start switching between the "Time" and "Date" screens and you should be able to see the issue.

Cheers
K

**Comment by AlexITMan** [comment]
@AmigoDeluxe,  thanks for the example. Now I understand the problem.

**Comment by AmigoDeluxe** [comment]
@AlexITMan very welcome!

**Comment by balancedkitchen** [comment]
https://x.thunkable.com/copy/c5177c0558012199d473a674c7741366
In an app, the created list is from 1 to 20. Add to the list  21 or remove 20 and see the result

**Comment by mark-friedman** [comment]
Thank you @AmigoDeluxe and @balancedkitchen!

**Comment by mark-friedman** [comment]
This should be fixed in the latest release.  Please reload your project in the browser, try it out and let me know the result.

**Comment by AmigoDeluxe** [comment]
Hey @balancedkitchen , you mention a list, this bug report is regarding text trimming in specific as requested by @mark-friedman so not sure how to implement what you describe in this scenario. 

@mark-friedman I slightly edited the "Text trim bug" project in order to update it (if this is what you meant by "reload the project in the browser") and tested it in the Companion app but I am still getting the same issue. Have you tested the "Text trim bug" app in your companion and saw that the issue is resolved? 

Thanks
K

**Comment by mark-friedman** [comment]
> Hey @balancedkitchen , you mention a list, this bug report is regarding text trimming in specific as requested by @mark-friedman so not sure how to implement what you describe in this scenario.
> Hey @balancedkitchen , you mention a list, this bug report is regarding text trimming in specific as requested by @mark-friedman so not sure how to implement what you describe in this scenario.

The text and list indexing issues have the same underlying cause, so both should now be fixed.

> @mark-friedman I slightly edited the "Text trim bug" project in order to update it (if this is what you meant by "reload the project in the browser") and tested it in the Companion app but I am still getting the same issue. Have you tested the "Text trim bug" app in your companion and saw that the issue is resolved?

By "reload the project in the browser", I mean to literally cause a browser reload.  The most effective way to do that is probably by just closing any tabs/windows that are running Thunkable ✕ in them and then reloading x.thunkable.com.  I did test the "Text trim bug" app in my companion and it worked for me.

**Comment by AmigoDeluxe** [comment]
Hi @mark-friedman 

Followed the steps you describe but still getting the same: When I update one screen the other breaks:
[One](https://dl.dropboxusercontent.com/s/5v875cpavrs882j/Screenshot_20190713_211646_com.thunkable.live.jpg)
[Two](https://dl.dropboxusercontent.com/s/6lp9acva6xp9icr/Screenshot_20190713_211654_com.thunkable.live.jpg)

Just curious, is Thunkable using different servers by continent? I am based in Europe and if so, could it be that your instances take time to sync release changes? 

Thanks
K

**Comment by mark-friedman** [comment]
> Just curious, is Thunkable using different servers by continent? I am based in Europe and if so, could it be that your instances take time to sync release changes?

@AmigoDeluxe What you are saying is possible.  We use Cloudflare to help distribute our code and there could be a delay, though it's usually not this long.  I suppose it is also possible that despite your doing a reload that you are still seeing an older version of Thunkable that was cached by your browser.  For this last case, one thing you could try is to delete all the data in your browser related to x.thunkable.com.  The method for doing that changes from browser to browser, so you might want to check on how to do that for your browser.

In the meantime I'm also checking to see if there is a way for you to obtain the version of Thunkable that you have running in your browser.

**Comment by AmigoDeluxe** [comment]
Hey @mark-friedman , I just cleaned up my browser's cache and retired but no love. Let's give it a day to see if it is a sync thing :-)

K

**Comment by mark-friedman** [comment]
Actually, I just discovered that the fix that I thought had gone into yesterday's release did not get into that release, but should get into our next release early next week.  So sorry about the confusion :-(

**Comment by AmigoDeluxe** [comment]
Ah ok then :-D

**Comment by balancedkitchen** [comment]
I still have the same problem!

**Comment by mark-friedman** [comment]
We are in the process of deploying a new release now.  It ought to be done by the end of the day.

**Comment by AmigoDeluxe** [comment]
Looks like it has been fixed. Can anyone else check as well?

**Comment by AlexITMan** [comment]
I just updated Thinkable Libe on Android and I see

![изображение](https://user-images.githubusercontent.com/20015046/61577557-b0b4f400-aaf1-11e9-9eea-de6580383331.png)

**Comment by AmigoDeluxe** [comment]
Try moving a block in the project and retesting. I believe this is necessary to update it properly.

**Comment by AlexITMan** [comment]
I always forget that I need to update the project.

Indeed, I do not see the error, but I will continue the tests.

**Comment by AmigoDeluxe** [comment]
Looks good. Closing the issue.
