### ISSUE TITLE
Scroll property

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#448]
### Platform
Android companion (Thunkable X)

### Issue/Request Origin
Scroll property not working too well after the last update

### Steps to Reproduce
1.Set a screen "scrolling" > True or Column component "Scroll" > true
2. Scroll till the bottom
3.

### Expected Behavior
to work as it were before the last update

### Actual Behavior
On screen it doesn't scroll till the bottom (completetly) and On column scroll it creates an White space uderneath the column or separation with the bottom, asuming is not filling the full height 

```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by josmas** [comment]
Thanks for the report @danielcoglitore We'll look into it.

**Comment by domhnallohanlon** [comment]
@danielcoglitore we just took another look at this and the scrolling looks like it's fixed now:
https://x.thunkable.com/projectPage/601d510c3d9b1e38ddcdde3d/

Scrolling works for on Thunkable Live 

Can we close this issue now?

**Comment by jane-d-alt** [comment]
Hi Daniel,

Since you didn't follow up saying that this behavior is still present in your apps, we're going to close this issue for now.

Thanks for reporting!
