### ISSUE TITLE
firebase sign in not working!

### ISSUE THREAD

**Issue by danielcoglitore** [thunkable/thunkable-issues#499]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):

The more info, the faster we will be able to address it!

### Platform
Android Companion

### Issue/Request Origin
Trying to sign in into firebase from the app

### Steps to Reproduce
1.Use sign in component
2. 
3.

### Project Link
Link to a project copy that shows this behaviour. This is important because most times we cannot reproduce the issues reported just with the list of steps, so please do provide this.

### Expected Behavior
What did you expect to happen?

### Actual Behavior
Gives a totally strange error 
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by jaredgib** [comment]
I can describe this further. 

I opened up a project with a firebase sign in component. Ran it on the live companion. App worked fine. Download to my android to see how it looked. I receive the message upon signing “verify your email”. Somehow I believe the app and check my email but there’s nothing there. So I figure I somehow changed the password. So I try to reset the password and see this 

![A2BA06A7-5311-4EE6-8CB0-14BD6C10128B](https://user-images.githubusercontent.com/58823942/81133332-486bbd80-8f1f-11ea-81b5-c92c15872ffe.jpeg)

Then I realize when I open the app, the verify email was displayed before I even clicked sign in. But this is an error flag and shouldn’t just be there. So I go back to the computer. Look around. Verify my password and the api key. Then Run it again on the live companion app. Works like a charm. So I download again to my android. Same issue as before. Go back to live app (on my iPhone) Works fine. Download to my iPhone and I have the exact same issue as on android. Go back to live app and it works just fine.

**Comment by danielcoglitore** [comment]
Thanks man ! you have more patience than me =D

**Comment by weihuali0509** [comment]
Looking into the issue 🚌

**Comment by Antoriccio9** [comment]
Hope my comment could give you more info:

I was testing my app yesterday at Midnight (Italian Time) and all of sudden I wasn't able to log in anymore, moreover I was unable to perform any action that included downloading data from firebase.

All my backups have the same problem.

My question is: If I had a built app, would it have experienced this problem?

**Comment by domhnallohanlon** [comment]
@Antoriccio9 this issue is now fixed. Can you try your project again and let us know whether or not it's working for you now. 
Thank.

**Comment by Antoriccio9** [comment]
Hi Dom, I tried 10 min ago and now ....Still not working

Thanks

**Comment by domhnallohanlon** [comment]
@Antoriccio9 this might be a separate issue? What are your debugging labels telling you?

**Comment by Antoriccio9** [comment]
I doubt it, everything was working yesterday and I didn't touch the code.
Moreover, all my backups have the same issue.

What are other users saying? 

I'm curious about one thing: If I had a built app, would it have experienced this problem?

**Comment by weihuali0509** [comment]
@Antoriccio9 are you using Android or iOS? You need to download the latest android companion in order for it to work? Our iOS companion is still pending for review.

**Comment by 22rdhall** [comment]
I am using iOS and having the same issue and message as jaredgib. My phone software is up to date. I noticed this yesterday.

![IMG_0654](https://user-images.githubusercontent.com/13912726/81205445-54dc2e80-8f90-11ea-8d80-df8c2c865436.jpg)

**Comment by app-vrb** [comment]
I confirm, I just tested and don't work.
It's really frustrating work like this, every day there is something doesn't work.

**Comment by weihuali0509** [comment]
If you are running on the iOS companion, the fix is on the way; We are still waiting for Apple to approve it. But the download version should work.

**Comment by Antoriccio9** [comment]
what about the live test from the pc? it is not working too

**Comment by weihuali0509** [comment]
@Antoriccio9 did you re-publish the web app? or do you have a project I can test?

**Comment by Antoriccio9** [comment]
Yes, i re published and i live tested it right now, but still not working.
https://x.thunkable.com/projects/5ea1e7c7f748de390c489eda/416ef494-f98f-47f1-a495-55f38d1ba2c2/designer

Here is the link to the app

**Comment by weihuali0509** [comment]
Can someone confirm if your Android or iOS companion work with Firebase? You need to have the lastest version v185 from the store.

Thanks,
Wei

**Comment by eoinparkinson** [comment]
I just updated the companion app half hour ago. Auth and DB work fine. iOS 13.3.1

**Comment by danielcoglitore** [comment]
@weihuali0509 Hi, yes is working fine! thanks! =D

**Comment by weihuali0509** [comment]
That is good to know. I am going to this issue now.

Thank you :)
Wei

**Comment by jbonet007** [comment]
My app is still not working.
exactly the same error.

**Comment by weihuali0509** [comment]
@jbonet007 do you update the Thunkable app to the latest version?

**Comment by 22rdhall** [comment]
My app is also not working. I am using v 185 and am on an iPhone 8 that is also fully updated. My app is not getting data from realtime db.

**Comment by weihuali0509** [comment]
We are still waiting for the iOS companion v186 to be approved in the App store.

**Comment by 22rdhall** [comment]
Downloaded v186 and it seems to be working now on iOS. Thank you and the staff for working hard on this one!
