### ISSUE TITLE
Delete row block doesn't work.

### ISSUE THREAD

**Issue by kjbuttel** [thunkable/thunkable-issues#535]
Thanks so much for filing an issue or feature request! Please fill out the following (wherever relevant):
The "delete row" block  for data viewer list doesn't work. It's set up to use a local database, and I've got the data being drawn down from airtable and filtered through an API request (since data filtering isn't available through the blocks for "Data Viewer List". When I try to delete a row on the local database, nothing happens. No data is effected or deleted.

### Platform
Thunkable ✕

### Issue/Request Origin
Building the apps.

### Steps to Reproduce
1. Open appointments
2. swipe left or right (have it enabled on both)
3.Try to delete the row.

### Project Link
https://x.thunkable.com/projects/5ec7169308a8c7019f886f2b/dcd6bdad-505d-45aa-af97-90a0106f5b6d/designer

The screen is called appointments. 

### Expected Behavior
I expected the row and data to be deleted.

### Actual Behavior
Nothing changed.
```
  STACK TRACE AND/OR SCREENSHOTS
```

**Comment by kjbuttel** [comment]
I am testing the app on an iPhone Xr.

**Comment by kjbuttel** [comment]
Just did some experimenting, and it turns out that if you download the built app on iphone, it works. The only portion that doesn't work is if you are using the "live test" program on an iphone through the thunkable app.

**Comment by athornock84037** [comment]
I have been working on this having issues. Here's a simplified app illustrating the issues.
https://x.thunkable.com/copy/25488bb5d044bc1237c60a8d96371c9d

I can only ever get it to delete 51 rows out of 100.

**Comment by athornock84037** [comment]
BTW, I downloaded the Android version and still had the same issues.

**Comment by danibarzo** [comment]
Hi friends @kjbuttel @athornock84037 @josmas  is the "delete row" component still not working right?

**Comment by josmas** [comment]
Thanks for the report, we will look into it.

**Comment by StevenPurn** [comment]
Is this only for local data sources? Does anyone have another example which isn't working? Seems the first project no longer exists.

@athornock84037 I believe your example doesn't work because you are iterating through a list that you are also removing items from. Ideally you would create a copy of the list which you use for iteration and then you remove the items from the original list. This can cause issues as each time you remove an item from the list the indices of the other items is changed. If you can describe what it is exactly that you're trying to accomplish we might be able to help you do so. 

I will see what we can do about your concerns for the other blocks that aren't working as you expect.

**Comment by athornock84037** [comment]
Good to know. And makes sense. I'll try what you stated.

**Comment by StevenPurn** [comment]
As far as I know, the update function should be working though it is always possible that something we are not yet aware of is misbehaving. Something to note is that you should be able to access rows by their index as well as their id. We did not support this previously but have added support sometime recently. 

Hm, I'm not sure I understand what you mean exactly when you say carry that info right on the row. Can you please clarify?

We do give you an id back when you create a row via our blocks. Do you mean you would like to be able to access the id directly somehow? Can you explain how you envision that working? Or even the use case you are trying to satisfy so we can investigate potential solutions?

**Comment by danibarzo** [comment]
Hi @StevenPurn. is the "delete row in" component from Data Sources still not working? I just one to use this function (delete one row) but it is not working for me, i am using airtable as Data Source. Thanks in advance!

**Comment by StevenPurn** [comment]
Hi @danibarzo! As far as I am aware, it is working. As of right now, you might still need to refresh the list in the app (if you are using a data viewer) to see the change reflected. If it isn't working for you can you let me know what your blocks look like or share your project so I can investigate?

**Comment by danibarzo** [comment]
Hi @StevenPurn. Actually now it is working for me! . I just realized yesterday and I didn't change anything in my blocks. Thanks for your help anyway!

**Comment by StevenPurn** [comment]
Glad to hear it is working for you! 

If anyone has an example of an app where it isn't working can they please share so I can investigate?

**Comment by StevenPurn** [comment]
I'm going to close this for now but if anyone has an example where it isn't working, please share here and we can get this reopened.
