### ISSUE TITLE
Camera will not stream on Webapp

### ISSUE THREAD

**Issue by fedegarcia30** [thunkable/thunkable-issues#763]
### Issue/Request Origin
Comminity

### Steps to Reproduce
1. Create a simple app to take a picture
2. Publish the app as mobile webapp
3. Use the webapp (android or iOs) there will be no stream of the camera so you dont know if you are pointing correctly the objetc you want to take the photo to.

### Project Link
https://x.thunkable.com/copy/51b4a0f690db0323d84b44600daf801c

### Expected Behavior
Once you click the take pic button, have the camera window open so you can actually point to the object you want to take the photo to.

### Actual Behavior
After a couple of seconds, a pic shows in the browers with the front camera image.
```
  STACK TRACE AND/OR SCREENSHOTS
```
![image](https://user-images.githubusercontent.com/30117644/101174191-d5a4fb00-3643-11eb-9153-39ca7c793f1a.png)

**Comment by fedegarcia30** [comment]
Hi Team, any update if this feature will be solved?

**Comment by jane-d-alt** [comment]
Hi there,

This behavior should be resolved now.
When I test this web app on mobile (Google Chrome browser, iOS), I can take a photo and show it in the app: 
https://thunkable.site/w/DQwE6BJNN

This web app is based on the following project
https://x.thunkable.com/projects/60117e39d547b700111a8b96/1d29742c-5f96-4dec-baf2-10377007191c/designer

Does this behavior seem to be resolved for you?

**Comment by fedegarcia30** [comment]
Hi

Im published the app as a respondive webapp and its still not working, the issue is there is no preview stream of the camara so you dont know what you are taking the photo to.

https://thunkable.site/w/9qc7NgrGk

Ive tested on PC and Iphone

**Comment by jane-d-alt** [comment]
OK, I understand that you are making a feature request and not a bug report. I have updated this Github issue accordingly.
We are not currently working on this feature. I will update here when this feature is being worked on.

**Comment by fedegarcia30** [comment]
Im not sure this is case...if you deploy the app as a mobile app either for iOs or Android, when you press take photo the camera preview will show up allowing you to point at what you are making the photo. It will also allow you to selecte the camera you want yo use.

In the webapp you cant either select the camera nor see the preview.
