### ISSUE TITLE
Duplicating a button does not retain its font style & weight

### ISSUE THREAD

**Issue by tatiang** [thunkable/thunkable-issues#773]
### Platform
Thunkable X

### Steps to Reproduce
1. Create a label. Set its font style to Italic and its font weight to Bold.
2. Duplicate the label.
3. The duplicate (copy) will not have Italic or Bold text.

### Expected Behavior
Copied components should retain the properties of the original component.

### Actual Behavior
See screenshot below (original label on top, copy on bottom).
```
  STACK TRACE AND/OR SCREENSHOTS
```
<img width="167" alt="Screen Shot 2020-12-12 at 1 41 39 PM" src="https://user-images.githubusercontent.com/10355498/101995611-073f4700-3c80-11eb-90cd-cefdd0723da9.png">

**Comment by tatiang** [comment]
I mentioned a label above but I'm finding this to still be an issue with buttons. If I set the background color, radius, font, font color, etc. in a button and then copy it, the copy does not retain those settings. It makes it tedious to duplicate existing components.

**Comment by jane-d-alt** [comment]
Hi there, it looks like this behavior has been resolved. Properties of Buttons and Labels are preserved when duplicated int he Design tab or with blocks. We will close this issue now. Apologies for not following up when this behavior was originally resolved.

Thanks,
Jane

**Comment by tatiang** [comment]
Thank you!

**Comment by tatiang** [comment]
While this does seem to be fixed for duplicating existing components, it's still an issue with custom Data Viewer layouts. See this forum topic for an example: https://community.thunkable.com/t/custom-data-viewer-layout-not-consistent/1307587.

**Comment by tatiang** [comment]
This appears to still be a problem with DVLs:

https://community.thunkable.com/t/custom-dvl-doesnt-save-styling/1322679

**Comment by tatiang** [comment]
I just had this happen again with a regular button (not a DVL). The default blue button with white text appeared after I duplicated a button that I had styled.

**Comment by tatiang** [comment]
This is still an issue when duplicating a button in the Snap to Place interface. If I remove the background color and border radius from a button and then duplicate it, the newly created button has a blue background and a border radius of 75.

In this screenshot, the original button is selected and the duplicate is to the right of it:

<img width="111" alt="image" src="https://user-images.githubusercontent.com/10355498/155047765-b6bae7b4-b4c9-42a1-b3ff-b2b43f3378b5.png">

**Comment by tatiang** [comment]
Also still a bug in the Drag & Drop interface. If I create a button and remove the background color and then duplicate it, the duplicate has a blue background.
