### ISSUE TITLE
Delete all rows does execute code in the 'do' area or after it. (Live, web preview)

### ISSUE THREAD

**Issue by cathysarisky** [thunkable/thunkable-issues#996]
### Platform
X. Happens on web preview and iOS Live.  Still need to test other platforms and downloads.

### Issue/Request Origin
https://community.thunkable.com/t/local-table-bugged-since-yesterday/1395502/7

### Steps to Reproduce
Create a local table and call "delete rows" - no code in the "do" block or after it will execute.

### Project Link
https://x.thunkable.com/copy/db0eb757ccc38e1f83a7aaf0ddd87e23
![image](https://user-images.githubusercontent.com/42299862/125610863-747f48b4-7816-4739-8d9c-c5241c28f698.png)

### Expected Behavior
both the 'do' contents and what's after the database block should happen.

### Actual Behavior
Neither does.

This may be related to #995  - but given it happens on Live, which #995 does not, I'm not sure.

**Comment by cathysarisky** [comment]
Update:  "Update value" also does not execute code that comes after it, although it does update the value.  (Tested on iOS 14.5, Live version 276-1.)

**Comment by cathysarisky** [comment]
Update: still broken on 278 Live.

**Comment by cis2131** [comment]
I have same problem.
Worked yesterday in live, but not in downloaded, today it dont work in latest companion version and downloaded.

**Comment by TacoNaco47** [comment]
Came across the same problem with a local data source. On Live Test it works like charm and I can see the data displayed: 
![image](https://user-images.githubusercontent.com/42797589/125836202-b3b013b8-099d-494f-b89e-82d4b6415fd0.png)
As soon as I try the same on my Android phone I get this ugly "No data found" message: 
![Screenshot_20210715_200703_com thunkable live](https://user-images.githubusercontent.com/42797589/125836423-e771213e-3ed1-46f1-9f8a-431dff0544e9.jpg)
Tested it on 279.

**Comment by bnice-msd** [comment]
I recorded these this afternoon. Referenced in post https://community.thunkable.com/t/create-row-problem-was-what-about-thunkable-that-is-not-working/1394583/36?u=bnice 
https://drive.google.com/file/d/1rr6h0BZM26O08ivRxyXROz3TKg4Urljm/view?usp=sharing 
https://drive.google.com/file/d/1tQ5-qHxUa-3rBkzSA0ebhun3gCPVX7GH/view?usp=sharing

**Comment by cis2131** [comment]
This issue has been resolved by thunkable yesterday.

**Comment by TacoNaco47** [comment]
@cis2131 In which version will it be resolved? 279 on Android has still the same behaviour.

**Comment by domhnallohanlon** [comment]
Thanks @cis2131 - yes, it should be working fine on Android and Web now, we're just waiting on the iOS Live app to be approved and it should be available there too. 

cc: @TacoNaco47 @bnice-msd @cathysarisky

**Comment by TacoNaco47** [comment]
@domhnallohanlon I'm afraid this issue isn't resolved in my case. I basically need the local data source as a table to get a key-value mapping for some HTTP data I am requesting via GET on an API. As you can see in this example, I get the data and parse it into a Data Viewer List and for comparison into a normal list with my for-each loop:
![image](https://user-images.githubusercontent.com/42797589/125946763-a64a2224-db5a-441d-bdab-17043af6a4fa.png)

So far, I managed to get this working **only once** in the Live Test preview (maybe by some sheer luck). However, the preview keeps crashing now and that even on the Android phone preview. This example is just a short abstract of what I did in the original app. But as you can see, it doesn't work under "basic" circumstances as well.

For better clarification, I shared the example: https://x.thunkable.com/copy/98c627f62b13f256f3fb26111c3687f5

PS: If you have a better idea to realise a key-value mapping I'm open to any suggestions. ;)

**Comment by cathysarisky** [comment]
I think there's a bug remaining that is causing data sources (maybe only local DB - not sure) to not update when Thunkable Live reloads.  (And data source caching has been an occasional gremlin I've seen on web preview before.)  You could test my hypothesis by uninstalling and reinstalling Thunkable Live which will reset any cached data.

Is ControllerList a local DB, or which data source type is it?

Actually, I think you're crashing because you're trying to treat app variable response as a list but it's actually an object.  If you want help debugging your code (rather than identifying Thunkable bugs), tag me over on the Thunkable forums.  (I'm @catsarisky)

**Comment by TacoNaco47** [comment]
@cathysarisky  Thanks for your help. I deleted the Thunkable Live app many times and it didn't help. :( As you suggested I started a new threat on the community forum (https://community.thunkable.com/t/get-requested-api-data-into-local-data-source-and-data-viewer-list/1399426) to keep this issue clean.
